function restoreButtons(data)
set(data.menus.editMenu.modeMenu.home,'Checked','on');
set(data.menus.editMenu.modeMenu.connect,'Checked','off');
set(data.menus.editMenu.modeMenu.id,'Checked','off');
set(data.menus.editMenu.modeMenu.review,'Checked','off');
set(data.buttons(1),'String','ID Materials','Visible','on',...
    'Enable','on','CallBack','briskit(''idMaterials'')','Interruptible','on');
set(data.buttons(2),'String','Show Outline','Visible','on',...
    'Enable','on','CallBack','briskit(''Outline'')','Interruptible','off');
set(data.buttons(3),'String','Review','Visible','on',...
    'Enable','on','CallBack','reviewRegions(''Init'')','Interruptible','on');
set(data.buttons(4),'String','Adjust Size','Visible','on',...
    'Enable','on','CallBack','Methods(''adjustSize'')','Interruptible','off');
set(data.buttons(5),'String','Manual','Visible','on',...
    'Enable','on','CallBack','briskit(''Manual'')','Interruptible','off');
set(data.buttons(6),'String','Other','Visible','on',...
    'Enable','on','CallBack','briskit(''Other'')','Interruptible','off');
set(data.buttons(7),'String','Save','Visible','on',...
    'Enable','on','CallBack','briskit(''Save'')');

end